---
install_packages:
  - awscli
  - bcc
  - bcc-tools
  - bmon
  - fatrace
  - fuse-sshfs
  - google-authenticator
  - htop
  - iftop
  - iotop
  - iptraf-ng
  - jq
  - kernel-devel
  - lokalize
  - meld
  - nautilus-open-terminal
  - nload
  - nmon
#  - ntop
  - perf
  - pigz
  - pxz
  - poedit
  - rkhunter
  - s3cmd
  - strace
  - stress
  - vim-common
  - vim-enhanced
  - vim-filesystem
  - wireshark
  - xorg-x11-server-Xvfb
  - moreutils
  - libfaketime
  - xz
