---
remove_packages:
  - evolution
  - fprintd

install_packages:
  - astronomy-backgrounds
  - desktop-backgrounds-basic
  - desktop-backgrounds-compat
  - desktop-backgrounds-gnome
  - earth-and-moon-backgrounds
  - earth-and-moon-backgrounds-common
  - earth-and-moon-backgrounds-dual
  - "f{{ ansible_distribution_major_version }}-backgrounds"
  - "f{{ ansible_distribution_major_version }}-backgrounds-animated"
  - "f{{ ansible_distribution_major_version }}-backgrounds-base"
  - "f{{ ansible_distribution_major_version }}-backgrounds-extras-base"
  - "f{{ ansible_distribution_major_version }}-backgrounds-extras-gnome"
  - "f{{ ansible_distribution_major_version }}-backgrounds-gnome"
  - fedora-workstation-backgrounds
  - ffmpeg
  - gedit-plugin-bookmarks
  - gedit-plugin-bracketcompletion
  - gedit-plugin-charmap
  - gedit-plugin-codecomment
  - gedit-plugin-colorpicker
  - gedit-plugin-colorschemer
  - gedit-plugin-commander
  - gedit-plugin-dashboard
  - gedit-plugin-drawspaces
  - gedit-plugin-findinfiles
  - gedit-plugin-git
  - gedit-plugin-joinlines
  - gedit-plugin-multiedit
  - gedit-plugins
  - gedit-plugins-data
  - gedit-plugin-smartspaces
  - gedit-plugin-synctex
  - gedit-plugin-terminal
  - gedit-plugin-textsize
  - gedit-plugin-wordcompletion
  - gedit-plugin-zeitgeist
  - glances
  - gnome-backgrounds
  - gnome-backgrounds-extras
  - gnome-music
  - gnome-shell-extension-background-logo
  - gnome-shell-extension-calc
  - gnome-shell-extension-gpaste
  - gnome-shell-extension-openweather
  - gnome-tweak-tool
  - gwenview
  - kernel-modules-extra
  - libreoffice-gallery-vrt-network-equipment
  - libreoffice
  - libreoffice-langpack-en
  - libreoffice-langpack-ro
  - libreoffice-wiki-publisher
  - lm_sensors
  - lshw
  - lynx
  - mc
  - mediawriter
  - 'mplayer*'
  - ntp
  - numad
  - numlockx
  - powertop
  - pulseaudio-equalizer
  - system-config-printer
  - tigervnc
  - tuned
  - 'vlc*'
  - 'wine*'
